SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `MallMAP` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `MallMAP`;

DROP TABLE IF EXISTS `FavoriteProduct`;
DROP TABLE IF EXISTS `FavoriteStore`;
DROP TABLE IF EXISTS `Product`;
DROP TABLE IF EXISTS `Store`;
DROP TABLE IF EXISTS `Floor`;
DROP TABLE IF EXISTS `Mall`;
DROP TABLE IF EXISTS `Category`;
DROP TABLE IF EXISTS `StoreCategory`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Role`;

CREATE TABLE `Role` (
  `RoleID` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleID`),
  UNIQUE KEY `RoleName_UNIQUE` (`RoleName`)
) ENGINE=InnoDB;

CREATE TABLE `User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `RoleID` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`UserID`),
  UNIQUE KEY `UserName_UNIQUE` (`UserName`),
  UNIQUE KEY `Email_UNIQUE` (`Email`),
  KEY `fk_Users_Role1_idx` (`RoleID`),
  CONSTRAINT `fk_Users_Role1`
    FOREIGN KEY (`RoleID`) REFERENCES `Role` (`RoleID`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `StoreCategory` (
  `StoreCategoryID` INT NOT NULL AUTO_INCREMENT,
  `StoreCategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StoreCategoryID`),
  UNIQUE KEY `StoreCategoryName_UNIQUE` (`StoreCategoryName`)
) ENGINE=InnoDB;

CREATE TABLE `Mall` (
  `MallID` INT NOT NULL AUTO_INCREMENT,
  `MallName` VARCHAR(255) NOT NULL,
  `Location` VARCHAR(255) NOT NULL,
  `IsPopular` TINYINT(1) NOT NULL DEFAULT 0,
  `MallImageURL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MallID`)
) ENGINE=InnoDB;

CREATE TABLE `Floor` (
  `FloorID` INT NOT NULL AUTO_INCREMENT,
  `FloorName` VARCHAR(100) NOT NULL,
  `MallID` INT NOT NULL,
  `FloorCode` VARCHAR(10) NOT NULL,
  `FloorOrder` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`FloorID`),
  UNIQUE KEY `Mall_FloorCode_UNIQUE` (`MallID`, `FloorCode`),
  KEY `fk_floor_Mall1_idx` (`MallID`),
  CONSTRAINT `fk_floor_Mall1`
    FOREIGN KEY (`MallID`) REFERENCES `Mall` (`MallID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `Store` (
  `StoreID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `StoreName` VARCHAR(255) NOT NULL,
  `StoreCategoryName` VARCHAR(255) NOT NULL,
  `StoreCategoryIcon` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'shopping-bag',
  `StoreCategoryID` INT NOT NULL,
  `Description` VARCHAR(255) NOT NULL DEFAULT '',
  `Phone` VARCHAR(20) NOT NULL DEFAULT '',
  `OpeningHours` VARCHAR(255) NOT NULL DEFAULT '',
  `LogoURL` VARCHAR(255) NOT NULL DEFAULT '',
  `MallID` INT NOT NULL,
  `FloorName` VARCHAR(100) NOT NULL,
  `FloorID` INT NOT NULL,
  `PosX` FLOAT NOT NULL DEFAULT 0,
  `PosY` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`StoreID`),
  KEY `fk_Store_User1_idx` (`UserID`),
  KEY `fk_Store_StoreCategory1_idx` (`StoreCategoryID`),
  KEY `fk_Store_floor1_idx` (`FloorID`),
  KEY `fk_Store_mall1_idx` (`MallID`),
  CONSTRAINT `fk_Store_User1`
    FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Store_StoreCategory1`
    FOREIGN KEY (`StoreCategoryID`) REFERENCES `StoreCategory` (`StoreCategoryID`)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Store_floor1`
    FOREIGN KEY (`FloorID`) REFERENCES `Floor` (`FloorID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_Store_Mall1`
    FOREIGN KEY (`MallID`) REFERENCES `Mall` (`MallID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CategoryID`),
  UNIQUE KEY `CategoryName_UNIQUE` (`CategoryName`)
) ENGINE=InnoDB;

CREATE TABLE `Product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(255) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `StockQuantity` INT NOT NULL DEFAULT 0,
  `ProductImageURL` VARCHAR(255) NOT NULL DEFAULT '',
  `StoreID` INT NOT NULL,
  `CategoryID` INT NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ProductID`),
  KEY `fk_Product_Category1_idx` (`CategoryID`),
  KEY `fk_Product_Store1_idx` (`StoreID`),
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`CategoryID`) REFERENCES `Category` (`CategoryID`)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_Store1`
    FOREIGN KEY (`StoreID`) REFERENCES `Store` (`StoreID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `FavoriteStore` (
  `FavoriteStoreID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  PRIMARY KEY (`FavoriteStoreID`),
  UNIQUE KEY `User_Store_UNIQUE` (`UserID`, `StoreID`),
  KEY `fk_FavoriteStore_User1_idx` (`UserID`),
  KEY `fk_FavoriteStore_Store1_idx` (`StoreID`),
  CONSTRAINT `fk_FavoriteStore_User1`
    FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_FavoriteStore_Store1`
    FOREIGN KEY (`StoreID`) REFERENCES `Store` (`StoreID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `FavoriteProduct` (
  `FavoriteProductID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`FavoriteProductID`),
  UNIQUE KEY `User_Product_UNIQUE` (`UserID`, `ProductID`),
  KEY `fk_FavoriteProduct_User1_idx` (`UserID`),
  KEY `fk_FavoriteProduct_Product1_idx` (`ProductID`),
  CONSTRAINT `fk_FavoriteProduct_User1`
    FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_FavoriteProduct_Product1`
    FOREIGN KEY (`ProductID`) REFERENCES `Product` (`ProductID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
